import { useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, BookOpen, Brain, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Flame, Home, Lightbulb, ListFilter, LockKeyhole, Medal, Play, RefreshCw, RotateCcw, Settings as SettingsIcon, ShieldCheck, Sparkles, Target, TimerReset, TrendingUp, Trophy, X } from 'lucide-react'
import { questions } from './data/questions'
import { loadHistory, loadSettings, resetData, saveHistory, saveSettings } from './lib/storage'
import type { AnswerHistory, ChoiceKey, Confidence, Question, Settings, Tab } from './types'

const nav: {id:Tab;label:string;icon:typeof Home}[]=[{id:'home',label:'ホーム',icon:Home},{id:'practice',label:'演習',icon:BookOpen},{id:'review',label:'復習',icon:RotateCcw},{id:'analytics',label:'分析',icon:BarChart3},{id:'settings',label:'設定',icon:SettingsIcon}]
const fieldColor:Record<string,string>={'セキュリティ':'bg-rose-50 text-rose-700','ネットワーク':'bg-sky-50 text-sky-700','データベース':'bg-violet-50 text-violet-700','経営戦略':'bg-amber-50 text-amber-700','基礎理論':'bg-cyan-50 text-cyan-700','プログラミング':'bg-indigo-50 text-indigo-700','プロジェクトマネジメント':'bg-orange-50 text-orange-700','コンピュータシステム':'bg-emerald-50 text-emerald-700'}

function App(){
 const [tab,setTab]=useState<Tab>('home'); const [history,setHistory]=useState<AnswerHistory[]>(loadHistory); const [settings,setSettings]=useState<Settings>(loadSettings)
 const [session,setSession]=useState<Question[]|null>(null); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<ChoiceKey|null>(null); const [confidence,setConfidence]=useState<Confidence>('normal'); const [result,setResult]=useState(false); const start=useRef(Date.now())
 useEffect(()=>saveHistory(history),[history]); useEffect(()=>saveSettings(settings),[settings])
 const startPractice=(items=questions)=>{setSession(items);setIndex(0);setSelected(null);setResult(false);start.current=Date.now();setTab('practice')}
 const answer=()=>{if(!selected||!session)return; const q=session[index]; const entry:AnswerHistory={id:crypto.randomUUID(),questionId:q.id,selectedAnswer:selected,isCorrect:selected===q.correctAnswer,confidence,elapsedSeconds:Math.max(1,Math.round((Date.now()-start.current)/1000)),answeredAt:new Date().toISOString()};setHistory(h=>[...h,entry]);setResult(true)}
 const next=()=>{if(!session)return;if(index>=session.length-1){setSession(null);setIndex(0);setSelected(null);setResult(false);setTab('home');return}setIndex(i=>i+1);setSelected(null);setResult(false);setConfidence('normal');start.current=Date.now()}
 const goTab=(id:Tab)=>{setTab(id);if(id!=='practice')setSession(null)}
 const title=session?'午前問題 演習':nav.find(n=>n.id===tab)?.label||''
 return <div className={settings.theme==='dark'?'dark bg-[#101713]':''}><div className="mx-auto min-h-screen max-w-[480px] bg-paper shadow-2xl dark:bg-[#101713] dark:text-white">
  <header className="safe-top fixed left-1/2 top-0 z-40 flex h-[76px] w-full max-w-[480px] -translate-x-1/2 items-center justify-between border-b border-black/5 bg-paper/95 px-5 backdrop-blur dark:bg-[#101713]/95">
   <div className="flex items-center gap-3">{session&&<button onClick={()=>setSession(null)} className="-ml-2 grid size-10 place-items-center rounded-full hover:bg-black/5"><ChevronLeft size={22}/></button>}<div><p className="text-[10px] font-bold tracking-[.18em] text-moss dark:text-lime">AP STUDY</p><h1 className="text-[17px] font-bold tracking-tight">{title}</h1></div></div>
   {session?<span className="tabular rounded-full bg-white px-3 py-1.5 text-xs font-bold shadow-sm dark:bg-white/10">{index+1} / {session.length}</span>:<button className="relative grid size-10 place-items-center rounded-full bg-white shadow-sm dark:bg-white/10"><Flame size={19} className="text-orange-500"/><span className="absolute -right-0.5 -top-0.5 size-2.5 rounded-full border-2 border-paper bg-lime"/></button>}
  </header>
  <main className={`px-4 pt-[92px] ${session?'pb-[138px]':'pb-[104px]'}`}>
   {tab==='home'&&<HomeScreen history={history} settings={settings} onStart={()=>startPractice()} onReview={()=>{setTab('review')}}/>}
   {tab==='practice'&&(session?<QuestionScreen question={session[index]} selected={selected} setSelected={setSelected} result={result} confidence={confidence} setConfidence={setConfidence}/>:<PracticeMenu onStart={startPractice}/>)}
   {tab==='review'&&<ReviewScreen history={history} onStart={startPractice}/>} {tab==='analytics'&&<Analytics history={history}/>} {tab==='settings'&&<SettingsScreen value={settings} onChange={setSettings} onReset={()=>{resetData();setHistory([]);setSettings(loadSettings())}}/>}
  </main>
  {session&&tab==='practice'?<div className="safe-bottom fixed bottom-0 left-1/2 z-50 w-full max-w-[480px] -translate-x-1/2 border-t border-black/5 bg-white/95 px-4 pt-3 backdrop-blur dark:bg-[#18211c]/95">{result?<button onClick={next} className="flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-ink font-bold text-white shadow-lg dark:bg-lime dark:text-ink">{index===session.length-1?'結果をみる':'次の問題へ'}<ChevronRight size={20}/></button>:<button disabled={!selected} onClick={answer} className="h-14 w-full rounded-2xl bg-ink font-bold text-white shadow-lg disabled:bg-slate-200 disabled:text-slate-400 dark:bg-lime dark:text-ink">解答する</button>}</div>:
  <nav className="safe-bottom fixed bottom-0 left-1/2 z-50 flex w-full max-w-[480px] -translate-x-1/2 justify-around border-t border-black/5 bg-white/95 px-1 pt-2 backdrop-blur dark:bg-[#18211c]/95">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>goTab(id)} className={`relative flex min-w-[62px] flex-col items-center gap-1 rounded-xl py-1.5 text-[10px] font-bold transition ${tab===id?'text-moss dark:text-lime':'text-slate-400'}`}>{tab===id&&<span className="absolute -top-2 h-0.5 w-8 rounded-full bg-moss dark:bg-lime"/>}<Icon size={21} strokeWidth={tab===id?2.5:2}/><span>{label}</span></button>)}</nav>}
 </div></div>
}

function HomeScreen({history,settings,onStart,onReview}:{history:AnswerHistory[];settings:Settings;onStart:()=>void;onReview:()=>void}){
 const correct=history.filter(h=>h.isCorrect).length, accuracy=history.length?Math.round(correct/history.length*100):0, wrongIds=new Set(history.filter(h=>!h.isCorrect).map(h=>h.questionId)); const days=new Set(history.map(h=>h.answeredAt.slice(0,10))).size
 const fieldStats=questions.map(q=>q.field).filter((v,i,a)=>a.indexOf(v)===i).map(field=>{const ids=new Set(questions.filter(q=>q.field===field).map(q=>q.id));const hs=history.filter(h=>ids.has(h.questionId));return{field,score:hs.length?Math.round(hs.filter(h=>h.isCorrect).length/hs.length*100):0,count:hs.length}}).sort((a,b)=>b.score-a.score)
 const examDays=Math.max(0,Math.ceil((new Date(settings.examDate).getTime()-Date.now())/86400000)); const possibility=history.length?Math.min(96,Math.round(accuracy*.72+Math.min(history.length,40)*.7)):42
 return <div className="space-y-4">
  <section className="overflow-hidden rounded-[28px] bg-ink p-5 text-white shadow-card relative"><div className="absolute -right-12 -top-16 size-48 rounded-full border-[30px] border-white/[.04]"/><div className="relative flex items-start justify-between"><div><p className="mb-1 text-xs font-medium text-white/60">合格可能性スコア</p><div className="flex items-end gap-2"><span className="tabular text-5xl font-bold tracking-tight">{possibility}</span><span className="mb-1.5 text-sm text-white/60">/ 100</span></div></div><div className="grid size-12 place-items-center rounded-2xl bg-lime text-ink"><TrendingUp size={23}/></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-lime transition-all" style={{width:`${possibility}%`}}/></div><div className="mt-3 flex justify-between text-[11px] text-white/60"><span>{history.length?'あと少し。弱点を集中対策しましょう':'まず10問解いて実力を測定'}</span><span>試験まで {examDays}日</span></div></section>
  <section className="grid grid-cols-2 gap-3"><Stat icon={Target} label="午前正答率" value={`${accuracy}%`} note={`${history.length}問に解答`} color="bg-emerald-50 text-moss"/><Stat icon={Brain} label="午後対策" value="2 / 5" note="選択分野を設定済み" color="bg-violet-50 text-violet-600"/></section>
  <section className="rounded-[24px] bg-[#e7f0c8] p-4"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/70 text-moss"><Sparkles size={20}/></div><div className="min-w-0 flex-1"><p className="text-[11px] font-bold text-moss">TODAY'S PLAN</p><h2 className="mt-0.5 font-bold">今日のおすすめ学習</h2><p className="mt-1 text-xs leading-relaxed text-slate-600">{wrongIds.size?`間違えた${wrongIds.size}問を解き直して、記憶を定着させましょう。`:'午前問題を10問解いて、あなたの得意・苦手を見つけましょう。'}</p></div></div><button onClick={wrongIds.size?onReview:onStart} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-ink text-sm font-bold text-white">{wrongIds.size?'復習をはじめる':'10問チャレンジ'}<ChevronRight size={17}/></button></section>
  <div className="flex items-center justify-between px-1 pt-1"><h2 className="font-bold">学習サマリー</h2><span className="text-xs text-slate-400">すべての期間</span></div>
  <section className="grid grid-cols-3 gap-2"><MiniStat icon={RotateCcw} value={wrongIds.size} label="復習待ち"/><MiniStat icon={Flame} value={days} label="学習日数"/><MiniStat icon={BookOpen} value={history.length} label="解答数"/></section>
  <section className="rounded-[24px] bg-white p-4 shadow-card dark:bg-white/5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">分野スナップショット</h2><button className="text-xs font-bold text-moss dark:text-lime">詳しく見る</button></div>{fieldStats.slice(0,3).map((f,i)=><div key={f.field} className="mb-3 last:mb-0"><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium">{i===0&&f.count>0?'得意 · ':i===2&&f.count>0?'要対策 · ':''}{f.field}</span><span className="tabular font-bold">{f.count?`${f.score}%`:'未測定'}</span></div><div className="h-1.5 rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-moss" style={{width:`${f.count?f.score:4}%`}}/></div></div>)}</section>
 </div>
}
function Stat({icon:Icon,label,value,note,color}:{icon:typeof Target;label:string;value:string;note:string;color:string}){return <div className="rounded-[22px] bg-white p-4 shadow-card dark:bg-white/5"><div className={`mb-3 grid size-9 place-items-center rounded-xl ${color}`}><Icon size={18}/></div><p className="text-[11px] text-slate-500">{label}</p><p className="tabular mt-0.5 text-2xl font-bold">{value}</p><p className="mt-1 truncate text-[10px] text-slate-400">{note}</p></div>}
function MiniStat({icon:Icon,value,label}:{icon:typeof Home;value:number;label:string}){return <div className="rounded-2xl border border-slate-100 bg-white p-3 text-center dark:border-white/5 dark:bg-white/5"><Icon size={17} className="mx-auto mb-1 text-moss dark:text-lime"/><p className="tabular text-xl font-bold">{value}</p><p className="text-[10px] text-slate-400">{label}</p></div>}

function PracticeMenu({onStart}:{onStart:(q?:Question[])=>void}){const fields=[...new Set(questions.map(q=>q.field))];return <div className="space-y-5"><div><p className="text-sm text-slate-500">いまの目的に合わせて</p><h2 className="mt-1 text-2xl font-bold tracking-tight">演習方法を選ぶ</h2></div><button onClick={()=>onStart()} className="relative w-full overflow-hidden rounded-[26px] bg-moss p-5 text-left text-white shadow-card"><div className="absolute -right-4 -top-6 grid size-28 place-items-center rounded-full bg-white/10"><Play size={38}/></div><span className="rounded-full bg-lime px-2.5 py-1 text-[10px] font-bold text-ink">おすすめ</span><h3 className="mt-4 text-xl font-bold">ランダム演習</h3><p className="mt-1 text-xs text-white/70">全分野からバランスよく8問出題</p><div className="mt-5 flex items-center gap-2 text-sm font-bold">演習をはじめる <ChevronRight size={17}/></div></button><div className="grid grid-cols-2 gap-3"><ModeCard icon={CalendarDays} title="年度別" text="令和6年 秋期" onClick={()=>onStart()}/><ModeCard icon={ListFilter} title="分野別" text={`${fields.length}分野から選択`} onClick={()=>onStart(questions.filter(q=>q.field==='セキュリティ'))}/><ModeCard icon={TimerReset} title="模擬試験" text="本番形式・80問" badge="準備中"/><ModeCard icon={RotateCcw} title="クイック復習" text="間違えた問題" onClick={()=>onStart()}/></div><div><h3 className="mb-3 font-bold">分野から選ぶ</h3><div className="flex flex-wrap gap-2">{fields.map(f=><button key={f} onClick={()=>onStart(questions.filter(q=>q.field===f))} className={`rounded-full px-3 py-2 text-xs font-bold ${fieldColor[f]||'bg-slate-100'}`}>{f}</button>)}</div></div><div className="rounded-2xl border border-slate-200 p-4 text-xs leading-relaxed text-slate-500 dark:border-white/10"><div className="mb-2 flex items-center gap-2 font-bold text-ink dark:text-white"><ShieldCheck size={17} className="text-moss"/>問題の出典について</div>出典：情報処理推進機構（IPA）<br/>問題文・選択肢はIPA公開資料より引用<br/>解説は本アプリが作成</div></div>}
function ModeCard({icon:Icon,title,text,onClick,badge}:{icon:typeof Home;title:string;text:string;onClick?:()=>void;badge?:string}){return <button onClick={onClick} disabled={!onClick} className="min-h-36 rounded-[22px] bg-white p-4 text-left shadow-card disabled:opacity-60 dark:bg-white/5"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-slate-100 text-moss dark:bg-white/10 dark:text-lime"><Icon size={20}/></div>{badge&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] text-slate-500">{badge}</span>}</div><p className="mt-4 font-bold">{title}</p><p className="mt-1 text-[11px] text-slate-400">{text}</p></button>}

function QuestionScreen({question,selected,setSelected,result,confidence,setConfidence}:{question:Question;selected:ChoiceKey|null;setSelected:(v:ChoiceKey)=>void;result:boolean;confidence:Confidence;setConfidence:(v:Confidence)=>void}){return <div className="space-y-4"><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${fieldColor[question.field]||'bg-slate-100'}`}>{question.field}</span><span className="tabular text-xs text-slate-400">令和{question.examYear-2018}年度 {question.examSeason}・問{question.questionNumber}</span></div><div className="rounded-[24px] bg-white p-5 shadow-card dark:bg-white/5"><p className="text-[15px] font-medium leading-[1.9]">{question.questionText}</p></div><div className="space-y-3">{question.choices.map(c=>{const isCorrect=result&&c.key===question.correctAnswer,isWrong=result&&c.key===selected&&selected!==question.correctAnswer,isSelected=selected===c.key;return <button key={c.key} disabled={result} onClick={()=>setSelected(c.key)} className={`flex min-h-[64px] w-full items-center gap-3 rounded-2xl border-2 p-3.5 text-left transition ${isCorrect?'border-emerald-500 bg-emerald-50':isWrong?'border-rose-400 bg-rose-50':isSelected?'border-moss bg-emerald-50/50':'border-transparent bg-white shadow-sm dark:bg-white/5'}`}><span className={`grid size-9 shrink-0 place-items-center rounded-xl text-sm font-bold ${isCorrect?'bg-emerald-500 text-white':isWrong?'bg-rose-400 text-white':isSelected?'bg-moss text-white':'bg-slate-100 text-slate-500 dark:bg-white/10'}`}>{isCorrect?<Check size={18}/>:isWrong?<X size={18}/>:c.key}</span><span className="text-[13px] font-medium leading-relaxed">{c.text}</span></button>})}</div>{!result?<div className="flex items-center justify-between rounded-2xl bg-white p-3 dark:bg-white/5"><span className="text-xs font-bold text-slate-500">自信度</span><div className="flex gap-1">{([['high','自信あり'],['normal','ふつう'],['low','自信なし']] as const).map(([v,l])=><button onClick={()=>setConfidence(v)} key={v} className={`rounded-lg px-2.5 py-2 text-[10px] font-bold ${confidence===v?'bg-ink text-white dark:bg-lime dark:text-ink':'bg-slate-100 text-slate-400 dark:bg-white/10'}`}>{l}</button>)}</div></div>:<Explanation question={question} selected={selected!}/>}<Source question={question}/></div>}
function Explanation({question,selected}:{question:Question;selected:ChoiceKey}){const ok=selected===question.correctAnswer;return <div className="space-y-3"><div className={`rounded-[24px] p-5 ${ok?'bg-emerald-50':'bg-rose-50'}`}><div className="flex items-center gap-3"><div className={`grid size-10 place-items-center rounded-full text-white ${ok?'bg-emerald-500':'bg-rose-400'}`}>{ok?<Check/>:<X/>}</div><div><p className={`text-xs font-bold ${ok?'text-emerald-700':'text-rose-600'}`}>{ok?'正解です！':'不正解'}</p><p className="mt-0.5 font-bold">正解は「{question.correctAnswer}」</p></div></div></div>{!ok&&<ExplainBlock icon={CircleHelp} title={`「${selected}」が違う理由`} text={question.wrongReasons[selected]||'設問の条件に当てはまりません。'} tone="text-rose-500"/>}<ExplainBlock icon={Check} title="正解の理由" text={question.explanation} tone="text-emerald-600"/><ExplainBlock icon={Lightbulb} title="覚えるポイント" text={question.memoryPoint} tone="text-amber-500"/><div className="rounded-2xl bg-white p-4 dark:bg-white/5"><p className="mb-2 text-xs font-bold text-slate-500">関連キーワード</p><div className="flex flex-wrap gap-2">{question.keywords.map(k=><span key={k} className="rounded-full bg-slate-100 px-2.5 py-1.5 text-[10px] font-bold dark:bg-white/10">#{k}</span>)}</div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-[10px] leading-relaxed text-amber-800">この解説はIPA公開資料を基にAIが作成した要約・補足です。正確性を保証するものではありません。必要に応じてIPA公式の解答例を確認してください。</div></div>}
function ExplainBlock({icon:Icon,title,text,tone}:{icon:typeof Home;title:string;text:string;tone:string}){return <div className="rounded-2xl bg-white p-4 shadow-sm dark:bg-white/5"><div className={`mb-2 flex items-center gap-2 text-xs font-bold ${tone}`}><Icon size={17}/>{title}</div><p className="text-xs leading-[1.8] text-slate-600 dark:text-slate-300">{text}</p></div>}
function Source({question}:{question:Question}){return <a href={question.sourceUrl} target="_blank" rel="noreferrer" className="block rounded-2xl border border-slate-200 p-4 text-[10px] leading-relaxed text-slate-500 dark:border-white/10"><span className="font-bold text-ink dark:text-white">出典：{question.sourceName}</span><br/>問題文・選択肢はIPA公開資料より引用<br/>解説は本アプリが作成</a>}

function ReviewScreen({history,onStart}:{history:AnswerHistory[];onStart:(q?:Question[])=>void}){const [filter,setFilter]=useState('すべて');const latest=new Map<string,AnswerHistory>();history.forEach(h=>latest.set(h.questionId,h));const wrong=questions.filter(q=>{const h=latest.get(q.id);return h&&!h.isCorrect});const low=questions.filter(q=>latest.get(q.id)?.confidence==='low');const fields=['すべて',...new Set(wrong.map(q=>q.field))];const shown=wrong.filter(q=>filter==='すべて'||q.field===filter);return <div className="space-y-5"><div className="grid grid-cols-3 gap-2"><ReviewCount value={wrong.length} label="不正解" color="text-rose-500"/><ReviewCount value={low.length} label="自信なし" color="text-amber-500"/><ReviewCount value={0} label="連続ミス" color="text-violet-500"/></div><div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar">{fields.map(f=><button key={f} onClick={()=>setFilter(f)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${filter===f?'bg-ink text-white dark:bg-lime dark:text-ink':'bg-white text-slate-500 dark:bg-white/5'}`}>{f}</button>)}</div>{shown.length?<div className="space-y-3">{shown.map(q=><div key={q.id} className="rounded-[22px] bg-white p-4 shadow-sm dark:bg-white/5"><div className="mb-3 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${fieldColor[q.field]}`}>{q.field}</span><span className="text-[10px] text-slate-400">令和6年 秋期 問{q.questionNumber}</span></div><p className="line-clamp-2 text-xs font-medium leading-relaxed">{q.questionText}</p><button onClick={()=>onStart([q])} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-100 text-xs font-bold text-moss dark:bg-white/10 dark:text-lime"><RefreshCw size={15}/>もう一度解く</button></div>)}</div>:<EmptyState icon={Trophy} title="復習待ちはありません" text="演習で間違えた問題がここに追加されます。" action="問題を解いてみる" onClick={()=>onStart()}/>}</div>}
function ReviewCount({value,label,color}:{value:number;label:string;color:string}){return <div className="rounded-2xl bg-white p-3 text-center shadow-sm dark:bg-white/5"><p className={`tabular text-2xl font-bold ${color}`}>{value}</p><p className="mt-0.5 text-[10px] text-slate-400">{label}</p></div>}
function EmptyState({icon:Icon,title,text,action,onClick}:{icon:typeof Home;title:string;text:string;action:string;onClick:()=>void}){return <div className="rounded-[26px] bg-white px-6 py-10 text-center shadow-card dark:bg-white/5"><div className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-moss"><Icon size={29}/></div><h3 className="mt-5 font-bold">{title}</h3><p className="mx-auto mt-2 max-w-64 text-xs leading-relaxed text-slate-400">{text}</p><button onClick={onClick} className="mt-6 h-12 rounded-xl bg-ink px-6 text-xs font-bold text-white dark:bg-lime dark:text-ink">{action}</button></div>}

function Analytics({history}:{history:AnswerHistory[]}){const days=new Set(history.map(h=>h.answeredAt.slice(0,10))).size;const data=[...new Set(questions.map(q=>q.field))].map(field=>{const ids=new Set(questions.filter(q=>q.field===field).map(q=>q.id));const h=history.filter(x=>ids.has(x.questionId));return{field,count:h.length,accuracy:h.length?Math.round(h.filter(x=>x.isCorrect).length/h.length*100):0,time:h.length?Math.round(h.reduce((s,x)=>s+x.elapsedSeconds,0)/h.length):0}}).sort((a,b)=>b.count-a.count);return <div className="space-y-5"><div className="grid grid-cols-2 gap-3"><Stat icon={CalendarDays} label="学習日数" value={`${days}日`} note="継続が力になります" color="bg-orange-50 text-orange-500"/><Stat icon={BookOpen} label="学習問題数" value={`${history.length}問`} note="今月の合計" color="bg-sky-50 text-sky-600"/></div><section className="rounded-[24px] bg-white p-4 shadow-card dark:bg-white/5"><h2 className="mb-5 font-bold">分野別正答率</h2><div className="space-y-4">{data.map(d=><div key={d.field}><div className="mb-1.5 flex justify-between text-xs"><span>{d.field}</span><span className="tabular font-bold">{d.count?`${d.accuracy}%`:'—'}</span></div><div className="h-2 rounded-full bg-slate-100 dark:bg-white/10"><div className={`h-full rounded-full ${d.accuracy>=70?'bg-moss':d.accuracy>=50?'bg-amber-400':'bg-rose-400'}`} style={{width:`${d.count?Math.max(4,d.accuracy):0}%`}}/></div>{d.count>0&&<p className="mt-1 text-right text-[9px] text-slate-400">平均 {d.time}秒 / {d.count}問</p>}</div>)}</div></section><section className="rounded-[24px] bg-ink p-5 text-white"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-lime text-ink"><Medal size={22}/></div><div><p className="text-[10px] font-bold text-lime">午後選択おすすめ</p><h3 className="font-bold">情報セキュリティ × ネットワーク</h3></div></div><p className="mt-4 text-xs leading-relaxed text-white/60">午前の学習結果と選択候補をもとに提案します。もう少し解答すると精度が上がります。</p></section><section className="rounded-[24px] border border-slate-200 p-5 dark:border-white/10"><div className="mb-3 flex items-center gap-2 font-bold"><Brain size={19} className="text-moss"/>苦手理由のサマリー</div><p className="text-xs leading-relaxed text-slate-500">{history.some(h=>!h.isCorrect)?'用語の意味が近い選択肢で迷う傾向があります。「違い」を一文で説明できるように復習しましょう。':'データがまだありません。10問ほど解くと、つまずき方の傾向を分析します。'}</p></section></div>}

function SettingsScreen({value,onChange,onReset}:{value:Settings;onChange:(s:Settings)=>void;onReset:()=>void}){const [confirm,setConfirm]=useState(false);const options=['情報セキュリティ','ネットワーク','データベース','プログラミング','プロジェクトマネジメント'];return <div className="space-y-4"><SettingCard title="学習目標" icon={Target}><label className="block text-xs font-bold text-slate-500">試験予定日<input type="date" value={value.examDate} onChange={e=>onChange({...value,examDate:e.target.value})} className="mt-2 h-12 w-full rounded-xl border-0 bg-slate-100 px-3 font-medium text-ink outline-none dark:bg-white/10 dark:text-white"/></label><label className="mt-4 block text-xs font-bold text-slate-500">1日の目標学習時間<div className="mt-2 flex gap-2">{[15,30,45,60].map(m=><button key={m} onClick={()=>onChange({...value,dailyMinutes:m})} className={`h-11 flex-1 rounded-xl text-xs font-bold ${value.dailyMinutes===m?'bg-moss text-white':'bg-slate-100 text-slate-500 dark:bg-white/10'}`}>{m}分</button>)}</div></label></SettingCard><SettingCard title="午後の選択候補" icon={BookOpen}><div className="flex flex-wrap gap-2">{options.map(o=>{const active=value.afternoonFields.includes(o);return <button key={o} onClick={()=>onChange({...value,afternoonFields:active?value.afternoonFields.filter(x=>x!==o):[...value.afternoonFields,o]})} className={`rounded-full px-3 py-2 text-xs font-bold ${active?'bg-moss text-white':'bg-slate-100 text-slate-500 dark:bg-white/10'}`}>{active&&'✓ '}{o}</button>})}</div></SettingCard><SettingCard title="表示テーマ" icon={Sparkles}><div className="grid grid-cols-2 gap-2">{(['light','dark'] as const).map(t=><button key={t} onClick={()=>onChange({...value,theme:t})} className={`h-12 rounded-xl text-xs font-bold ${value.theme===t?'bg-ink text-white ring-2 ring-lime ring-offset-2':'bg-slate-100 text-slate-500 dark:bg-white/10'}`}>{t==='light'?'ライト':'ダーク'}</button>)}</div></SettingCard><div className="rounded-[24px] bg-white p-5 dark:bg-white/5"><div className="flex items-center gap-2 font-bold"><LockKeyhole size={18} className="text-moss"/>データ管理</div><p className="mt-2 text-[11px] leading-relaxed text-slate-400">学習データはこの端末のブラウザ内に保存されています。</p>{confirm?<div className="mt-4 rounded-xl bg-rose-50 p-3"><p className="text-xs font-bold text-rose-600">本当にすべて削除しますか？</p><div className="mt-3 flex gap-2"><button onClick={()=>setConfirm(false)} className="h-10 flex-1 rounded-lg bg-white text-xs font-bold">キャンセル</button><button onClick={()=>{onReset();setConfirm(false)}} className="h-10 flex-1 rounded-lg bg-rose-500 text-xs font-bold text-white">削除する</button></div></div>:<button onClick={()=>setConfirm(true)} className="mt-4 h-11 w-full rounded-xl border border-rose-200 text-xs font-bold text-rose-500">学習データをリセット</button>}</div><p className="pb-3 text-center text-[10px] text-slate-400">AP Study MVP · Local data only</p></div>}
function SettingCard({title,icon:Icon,children}:{title:string;icon:typeof Home;children:React.ReactNode}){return <section className="rounded-[24px] bg-white p-5 shadow-sm dark:bg-white/5"><div className="mb-5 flex items-center gap-2 font-bold"><Icon size={18} className="text-moss dark:text-lime"/>{title}</div>{children}</section>}
export default App
